import { buildPdfDocument, PDF_COLORS, PDF_PAGE_HEIGHT, PDF_PAGE_WIDTH, pdfRectangleCommand, pdfTextCommand, wrapPdfText } from "@/lib/pdf-document";

export type DonationReceiptDownloadRecord = {
  donationId: string;
  receiptNumber: string;
  issuedAt: Date;
  emailedAt: Date | null;
  payload: unknown;
  donorName: string | null;
  donorEmail: string | null;
  amount: string | number;
  currency: string;
  status: string;
  createdAt: Date;
  campaignTitle: string;
  campaignSlug: string;
  organizationName: string;
};

function metadataRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

function metadataString(metadata: unknown, key: string) {
  const value = metadataRecord(metadata)[key];

  return typeof value === "string" ? value : null;
}

function formatCurrency(value: string | number, currency: string) {
  const parsed = typeof value === "number" ? value : Number(value);

  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: currency || "IDR",
    currencyDisplay: "code",
    maximumFractionDigits: 0
  }).format(Number.isFinite(parsed) ? parsed : 0);
}

function formatDate(value: Date) {
  return value.toISOString().slice(0, 10);
}

export function donationReceiptFilename(receipt: Pick<DonationReceiptDownloadRecord, "receiptNumber">) {
  const safeNumber = receipt.receiptNumber
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return `terumbu-receipt-${safeNumber || "donation"}.pdf`;
}

export function donationReceiptHolderName(receipt: Pick<DonationReceiptDownloadRecord, "donorEmail" | "donorName">) {
  return receipt.donorName || receipt.donorEmail || "Terumbu.eco supporter";
}

export function donationReceiptProviderReference(receipt: Pick<DonationReceiptDownloadRecord, "payload">) {
  return metadataString(receipt.payload, "providerReference") ?? metadataString(receipt.payload, "paymentReference") ?? "Recorded";
}

export function buildDonationReceiptDownloadPdf(receipt: DonationReceiptDownloadRecord, origin = "https://terumbu.eco") {
  const holderName = donationReceiptHolderName(receipt);
  const providerReference = donationReceiptProviderReference(receipt);
  const issuedAt = formatDate(receipt.issuedAt);
  const campaignUrl = `${origin}/campaigns/${receipt.campaignSlug}`;
  const rows = [
    ["Campaign", receipt.campaignTitle],
    ["Campaign URL", campaignUrl],
    ["Partner", receipt.organizationName],
    ["Amount", formatCurrency(receipt.amount, receipt.currency)],
    ["Status", receipt.status],
    ["Issued", issuedAt],
    ["Provider reference", providerReference],
    ["Donor email", receipt.donorEmail ?? "Not recorded"]
  ];
  const commands = [
    pdfRectangleCommand(0, 0, PDF_PAGE_WIDTH, PDF_PAGE_HEIGHT, PDF_COLORS.sand),
    pdfRectangleCommand(48, 80, 499, 682, PDF_COLORS.white, PDF_COLORS.border),
    pdfTextCommand({ text: "Terumbu.eco Donation Receipt", x: 76, y: 722, size: 11, font: "bold", color: PDF_COLORS.coral }),
    pdfTextCommand({ text: receipt.receiptNumber, x: 76, y: 684, size: 28, font: "bold" }),
    pdfTextCommand({ text: holderName, x: 76, y: 654, size: 18, font: "bold", color: PDF_COLORS.kelp })
  ];
  let y = 594;

  rows.forEach(([label, value]) => {
    const wrappedValue = wrapPdfText(value, 292, 11);

    commands.push(pdfTextCommand({ text: label, x: 76, y, size: 10, font: "bold", color: PDF_COLORS.muted }));
    wrappedValue.forEach((line, index) => {
      commands.push(pdfTextCommand({ text: line, x: 230, y: y - index * 15, size: 11, font: "bold" }));
    });
    y -= Math.max(30, wrappedValue.length * 15 + 10);
  });

  commands.push(pdfRectangleCommand(76, 128, 443, 62, PDF_COLORS.seal));
  wrapPdfText("This receipt is generated from the Terumbu.eco donation and payment records connected to this account.", 393, 11).forEach((line, index) => {
    commands.push(pdfTextCommand({ text: line, x: 100, y: 164 - index * 15, size: 11, font: "bold", color: PDF_COLORS.ocean }));
  });
  commands.push(pdfTextCommand({ text: "Generated by Terumbu.eco", x: 76, y: 102, size: 9, color: PDF_COLORS.muted }));

  return buildPdfDocument(commands.join("\n"));
}
